export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  INVALID_PARAMS: "INVALID_PARAMS",

  UNAUTHORIZED: "UNAUTHORIZED",

  FORBIDDEN: "FORBIDDEN",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  DESTINATION_NOT_FOUND: "DESTINATION_NOT_FOUND",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  TOUR_NOT_FOUND: "TOUR_NOT_FOUND",

  TOUR_SCHEDULE_NOT_FOUND: "TOUR_SCHEDULE_NOT_FOUND",

  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",

  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",

  FAVORITE_NOT_FOUND: "FAVORITE_NOT_FOUND",

  POST_NOT_FOUND: "POST_NOT_FOUND",

  CONTACT_REQUEST_NOT_FOUND: "CONTACT_REQUEST_NOT_FOUND",

  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",

  REVIEW_NOT_ALLOWED: "REVIEW_NOT_ALLOWED",

  FAVORITE_ALREADY_EXISTS: "FAVORITE_ALREADY_EXISTS",

  NOT_ENOUGH_SEATS: "NOT_ENOUGH_SEATS",

  TOUR_SCHEDULE_NOT_OPEN: "TOUR_SCHEDULE_NOT_OPEN",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",

  INVALID_TOKEN: "INVALID_TOKEN",

  EXPIRED_TOKEN: "EXPIRED_TOKEN",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  DATABASE_ERROR: "DATABASE_ERROR",

  PERMISSION_DENIED: "PERMISSION_DENIED",

  FILE_REQUIRED: "FILE_REQUIRED",

  INVALID_IMAGE_FILE: "INVALID_IMAGE_FILE",

  CLOUDINARY_NOT_CONFIGURED: "CLOUDINARY_NOT_CONFIGURED",
} as const;
